[package]
name = "gitja"
version = "0.3.0"
edition = "2021"
authors = ["Matt Colligan <mcol@posteo.net>"]
description = "ğŸ™ Templated web page generator for your git repositories"
documentation = "https://gitja.mcol.xyz"
homepage = "https://gitja.mcol.xyz"
readme = "README.rst"
repository = "https://github.com/m-col/gitja"
license = "MIT"

# TODO: Add keywords & categories

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
